version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: server
    command: npm run start:server
    restart: "no"
    volumes:
      - ./packages/server:/root/app/packages/server:ro
      - ./packages/shared:/root/app/packages/shared:ro
    ports:
      - 8000:8000
    env_file:
      - ./environment/.env.default
      - ./environment/.env.server
